### ISSUE TITLE
MobilePreview: Scaling issues

### ISSUE THREAD

**Issue by ste7-ui** [arco-design/easy-email#116]
Hi,
in my context, when switching into mobile preview, the email template does not fit container:
![image](https://user-images.githubusercontent.com/63000088/170003904-de475e49-39e5-4fd8-abb5-45e3831017f4.png)

It seems to be due to the `scale` _css_ property approach.

As you can see, the visual editor header seems to be in a negative margin also , causing header to be _trimmed_.

Thanks

**Comment by m-Ryan** [comment]
It's looks like a bug, please provide a reproduced example.

**Comment by ste7-ui** [comment]
Sure!
[StackBlitz](https://stackblitz.com/edit/react-ts-umjt3b?file=App.tsx)
![image](https://user-images.githubusercontent.com/63000088/170241299-94fab11c-ae67-405f-9a6a-b1ba8afaf6ee.png)

I didn't make the buttons header bar overflowing to top, but this seems to be related to event bubbling/focus repositioning: I've noticed in my app, when I click on the preview buttons, system scrolls the page to the preview container, but overflow issues happens only in moblie preview:
![reposition-issue](https://user-images.githubusercontent.com/63000088/170242354-bcccef66-3117-4c9c-9e1e-8e6c9ed5b5a3.gif)


By this StackBlitz you can see also the #117 issue

**Comment by ste7-ui** [comment]
As you can see by your screenshot also, the buttons header bar in mobile preview is being trimmed at top

**Comment by m-Ryan** [comment]
Fixed now, please upgrade to the latest version.

```
   "easy-email-editor": "^4.1.10",
```

**Comment by ste7-ui** [comment]
Just udated, but still experiencing the right empty margin issue:

![image](https://user-images.githubusercontent.com/63000088/170497528-59df70f3-5957-4991-a755-04d7c641051a.png)

The blitz I've previously shared it is updated showing the issue

**Comment by ste7-ui** [comment]
Seems working fine now!
Thanks 😃
